export const orderData = {
    "11194001": {
      id: "11194001",
      status: "confirmed",
      statusText: "Confirmed",
      orderDate: "2024-01-15",
      estimatedDelivery: "2024-01-25",
      totalWeight: "500 MT",
      totalAmount: "GH₵ 25,000",
      products: [
        { name: "Yellow maize", quantity: "200 MT", price: "GH₵ 10,000", image: "/corn-kernels.png" },
        { name: "Cassava", quantity: "150 MT", price: "GH₵ 7,500", image: "/placeholder-nll04.png" },
        { name: "Ground nuts", quantity: "150 MT", price: "GH₵ 7,500", image: "/placeholder-y17cz.png" },
      ],
      supplier: {
        name: "Ashanti Agricultural Co.",
        contact: "+233 244 123 456",
        email: "info@ashantiagri.com",
        location: "Kumasi, Ghana",
      },
      tracking: {
        currentLocation: { lat: 6.6885, lng: -1.6244, name: "Kumasi" },
        destination: { lat: 5.6037, lng: -0.187, name: "Accra" },
        progress: 45,
        estimatedArrival: "2024-01-25 14:00",
      },
      weighBill: {
        billNumber: "WB-2024-001234",
        issueDate: "2024-01-16",
        weighingStation: "Kumasi Central Weighbridge",
        stationAddress: "Industrial Area, Kumasi, Ghana",
        stationLicense: "GHA-WB-2024-089",
        vehicleDetails: {
          plateNumber: "GR 1234-24",
          driverName: "Kwame Asante",
          driverLicense: "DL-2019-456789",
          vehicleType: "Heavy Duty Truck",
          tareWeight: "8,500 kg",
        },
        measurements: [
          {
            product: "Yellow maize",
            grossWeight: "28,500 kg",
            tareWeight: "8,500 kg",
            netWeight: "20,000 kg",
            moisture: "12.5%",
            quality: "Grade A",
          },
          {
            product: "Cassava",
            grossWeight: "23,500 kg",
            tareWeight: "8,500 kg",
            netWeight: "15,000 kg",
            moisture: "65.2%",
            quality: "Premium",
          },
          {
            product: "Ground nuts",
            grossWeight: "23,500 kg",
            tareWeight: "8,500 kg",
            netWeight: "15,000 kg",
            moisture: "8.1%",
            quality: "Grade A",
          },
        ],
        totalNetWeight: "50,000 kg",
        certifiedBy: "Samuel Osei",
        certifierLicense: "CW-2023-1156",
        timestamp: "2024-01-16 09:45:00",
        qrCode: "WB2024001234KUM",
      },
    },
    "01188144": {
      id: "01188144",
      status: "in-transit",
      statusText: "In Transit",
      orderDate: "2024-01-10",
      estimatedDelivery: "2024-01-22",
      totalWeight: "280 MT",
      totalAmount: "GH₵ 18,000",
      products: [
        { name: "Cassava", quantity: "100 MT", price: "GH₵ 6,000", image: "/placeholder-nll04.png" },
        { name: "White maize", quantity: "80 MT", price: "GH₵ 5,000", image: "/corn-kernels.png" },
        { name: "Corn", quantity: "60 MT", price: "GH₵ 4,000", image: "/corn-kernels.png" },
        { name: "Sesame", quantity: "40 MT", price: "GH₵ 3,000", image: "/placeholder-y17cz.png" },
      ],
      supplier: {
        name: "Northern Farms Ltd.",
        contact: "+233 244 987 654",
        email: "orders@northernfarms.gh",
        location: "Tamale, Ghana",
      },
      tracking: {
        currentLocation: { lat: 7.3599, lng: -2.4833, name: "Sunyani" },
        destination: { lat: 5.6037, lng: -0.187, name: "Accra" },
        progress: 65,
        estimatedArrival: "2024-01-22 10:30",
      },
      weighBill: {
        billNumber: "WB-2024-001189",
        issueDate: "2024-01-11",
        weighingStation: "Tamale Regional Weighbridge",
        stationAddress: "Northern Industrial Zone, Tamale, Ghana",
        stationLicense: "GHA-WB-2024-067",
        vehicleDetails: {
          plateNumber: "NR 5678-24",
          driverName: "Ibrahim Mohammed",
          driverLicense: "DL-2020-789123",
          vehicleType: "Articulated Truck",
          tareWeight: "12,000 kg",
        },
        measurements: [
          {
            product: "Cassava",
            grossWeight: "22,000 kg",
            tareWeight: "12,000 kg",
            netWeight: "10,000 kg",
            moisture: "68.1%",
            quality: "Premium",
          },
          {
            product: "White maize",
            grossWeight: "20,000 kg",
            tareWeight: "12,000 kg",
            netWeight: "8,000 kg",
            moisture: "13.2%",
            quality: "Grade A",
          },
          {
            product: "Corn",
            grossWeight: "18,000 kg",
            tareWeight: "12,000 kg",
            netWeight: "6,000 kg",
            moisture: "14.1%",
            quality: "Grade B",
          },
          {
            product: "Sesame",
            grossWeight: "16,000 kg",
            tareWeight: "12,000 kg",
            netWeight: "4,000 kg",
            moisture: "6.5%",
            quality: "Premium",
          },
        ],
        totalNetWeight: "28,000 kg",
        certifiedBy: "Fatima Abdul-Rahman",
        certifierLicense: "CW-2023-0892",
        timestamp: "2024-01-11 14:20:00",
        qrCode: "WB2024001189TAM",
      },
    },
  }